version: "3"
services:
  node-app:
    depends_on:
      - postgres
      - redis
    container_name: node-app-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongo-data:/data/db
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "88:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
# volumes:
#   mongo-data:
